"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.CustomerSearch=(function(TargetNS){var BackupData={CustomerInfo:'',CustomerEmail:'',CustomerKey:''},CustomerFieldChangeRunCount={};function DeactivateSelectionCustomerID(){if($('#TemplateSelectionCustomerID').length){$('#SelectionCustomerID').prop('disabled',true)
$('#SelectionCustomerID').prop('title',Core.Language.Translate('First select a customer user, then select a customer ID to assign to this ticket.'));$('#SelectionCustomerID').addClass('Disabled');}}
function ActivateSelectionCustomerID(){if($('#TemplateSelectionCustomerID').length&&$('#SelectionCustomerID').hasClass('Disabled')){$('#SelectionCustomerID').prop('disabled',false)
$('#SelectionCustomerID').prop('title',Core.Language.Translate('Select a customer ID to assign to this ticket.'));$('#SelectionCustomerID').removeClass('Disabled');}}
function GetCustomerInfo(CustomerUserID){var Data={Action:'AgentCustomerSearch',Subaction:'CustomerInfo',CustomerUserID:CustomerUserID},SignatureURL;Core.AJAX.FunctionCall(Core.Config.Get('Baselink'),Data,function(Response){$('#CustomerID').val(Response.CustomerID);$('#ShowCustomerID').html(Response.CustomerID);Core.App.Publish('Event.Agent.CustomerSearch.GetCustomerInfo.Callback',[Response.CustomerID]);$('#CustomerInfo .Content').html(Response.CustomerTableHTMLString);if(Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketPhone'){$('#ServiceID').attr('selectedIndex',0);Core.AJAX.FormUpdate($('#CustomerID').closest('form'),'AJAXUpdate','ServiceID',['Dest','SelectedCustomerUser','Signature','NextStateID','PriorityID','ServiceID','SLAID','CryptKeyID','OwnerAll','ResponsibleAll','TicketFreeText1','TicketFreeText2','TicketFreeText3','TicketFreeText4','TicketFreeText5','TicketFreeText6','TicketFreeText7','TicketFreeText8','TicketFreeText9','TicketFreeText10','TicketFreeText11','TicketFreeText12','TicketFreeText13','TicketFreeText14','TicketFreeText15','TicketFreeText16']);if($('#Dest').val()!==''){SignatureURL=Core.Config.Get('Baselink')+'Action='+Core.Config.Get('Action')+';Subaction=Signature;Dest='+$('#Dest').val()+';SelectedCustomerUser='+$('#SelectedCustomerUser').val();if(!Core.Config.Get('SessionIDCookie')){SignatureURL+=';'+Core.Config.Get('SessionName')+'='+Core.Config.Get('SessionID');}
$('#Signature').attr('src',SignatureURL);}}
if(Core.Config.Get('Action')==='AgentTicketProcess'&&typeof Core.Config.Get('CustomerFieldsToUpdate')!=='undefined'){$('#ServiceID').attr('selectedIndex',0);Core.AJAX.FormUpdate($('#CustomerID').closest('form'),'AJAXUpdate','ServiceID',Core.Config.Get('CustomerFieldsToUpdate'));}});}
function GetCustomerTickets(CustomerUserID,CustomerID){var Data={Action:'AgentCustomerSearch',Subaction:'CustomerTickets',CustomerUserID:CustomerUserID,CustomerID:CustomerID};if(typeof Core.Config.Get('CustomerSearch')!=='undefined'&&!parseInt(Core.Config.Get('CustomerSearch').ShowCustomerTickets,10)){return;}
function CustomerHistoryEvents(){$('select[name=ResponseID]').on('change',function(){var URL;if($(this).val()>0){URL=Core.Config.Get('Baselink')+$(this).parents().serialize();Core.UI.Popup.OpenPopup(URL,'TicketAction');$(this).val('0');}});$('select[name=ResponseID]').on('click',function(Event){Event.stopPropagation();return false;});$('#CustomerTickets .MasterAction').on('click',function(Event){var $MasterActionLink=$(this).find('a.MasterActionLink');if($(Event.target).hasClass('InputField_Search')){return true;}
if(Core.Config.Get('Action')==='AgentTicketCustomer'){Core.UI.Popup.ExecuteInParentWindow(function(WindowObject){WindowObject.Core.UI.Popup.FirePopupEvent('URL',{URL:$MasterActionLink.attr('href')});});Core.UI.Popup.ClosePopup();return false;}
else{if(Event.target!==$MasterActionLink.get(0)){window.location=$MasterActionLink.attr('href');return false;}}});$("#SortBy").off('change').on('change',function(){var SortedData,Selection=$(this).val().split('|');if(Selection.length===2){SortedData={Action:'AgentCustomerSearch',Subaction:'CustomerTickets',CustomerUserID:CustomerUserID,CustomerID:CustomerID,SortBy:Selection[0],OrderBy:Selection[1]};Core.AJAX.FunctionCall(Core.Config.Get('Baselink'),SortedData,function(Response){if($('#CustomerTickets').length){$('#CustomerTickets').html(Response.CustomerTicketsHTMLString);ReplaceCustomerTicketLinks();}});}});Core.UI.InputFields.Activate();Core.App.Subscribe('Event.UI.Accordion.OpenElement',function($Element){Core.UI.InputFields.Activate($Element);});}
function ReplaceCustomerTicketLinks(){$('#CustomerTickets').find('.AriaRoleMain').removeAttr('role').removeClass('AriaRoleMain');$('#CustomerTickets').find('.OverviewZoom a, .Pagination a, .TableSmall th a').click(function(){var Link=$(this).attr('href'),URLComponents;URLComponents=Link.split('?',2);Core.AJAX.FunctionCall(URLComponents[0],URLComponents[1],function(Response){if($('#CustomerTickets').length){$('#CustomerTickets').html(Response.CustomerTicketsHTMLString);ReplaceCustomerTicketLinks();$('#CustomerTickets a.SplitSelection').off('click').on('click',function(){Core.Agent.TicketSplit.OpenSplitSelection($(this).attr('href'));return false;});}});return false;});Core.UI.Accordion.Init($('.Preview > ul'),'li h3 a','.HiddenBlock');if(Core.Config.Get('Action')==='AgentTicketPhone'||Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketCustomer'||Core.Config.Get('Action')==='AgentChatAppend')
{CustomerHistoryEvents();}
return false;}
Core.AJAX.FunctionCall(Core.Config.Get('Baselink'),Data,function(Response){if($('#CustomerTickets').length){$('#CustomerTickets').html(Response.CustomerTicketsHTMLString);ReplaceCustomerTicketLinks();$('#CustomerTickets a.AsPopup').off('click').on('click',function(){Core.UI.Popup.OpenPopup($(this).attr('href'),'Action');return false;});$('#CustomerTickets a.SplitSelection').off('click').on('click',function(){Core.Agent.TicketSplit.OpenSplitSelection($(this).attr('href'));return false;});}});}
function CheckPhoneCustomerCountLimit(){if(Core.Config.Get('Action')!=='AgentTicketPhone'){return;}
if(parseInt(Core.Config.Get('CustomerSearch').AllowMultipleFrom,10)){return;}
if($('#TicketCustomerContentFromCustomer input.CustomerTicketText').length>0){$('#FromCustomer').val('').prop('disabled',true).prop('readonly',true);$('#Dest').trigger('focus');}
else{$('#FromCustomer').val('').prop('disabled',false).prop('readonly',false);}}
TargetNS.InitSimple=function($Element){var CustomerSearchType=$Element.data('customer-search-type');if(CustomerSearchType){Core.UI.Autocomplete.Init($Element,function(Request,Response){var URL=Core.Config.Get('Baselink'),Data={Action:'AgentCustomerSearch',Subaction:'Search'+CustomerSearchType,Term:Request.term,MaxResults:Core.UI.Autocomplete.GetConfig('MaxResultsDisplayed')};$Element.data('AutoCompleteXHR',Core.AJAX.FunctionCall(URL,Data,function(Result){var ValueData=[];$Element.removeData('AutoCompleteXHR');$.each(Result,function(){ValueData.push({label:this.Label+(CustomerSearchType=='CustomerUser'?' ('+this.Value+')':''),value:this.Value});});Response(ValueData);}));},function(Event,UI){$Element.val(UI.item.value).trigger('select.Autocomplete');Event.preventDefault();Event.stopPropagation();return false;},'CustomerSearch');}}
TargetNS.Init=function($Element){var AutocompleteFocus=false;if(Core.Config.Get('Action')==='AgentTicketCustomer'){GetCustomerTickets($('#CustomerAutoComplete').val(),$('#CustomerID').val());$Element.blur(function(){if($Element.val()===''){TargetNS.ResetCustomerInfo();DeactivateSelectionCustomerID();$('#CustomerTickets').empty();}});}
if((Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketPhone')&&$('#SelectedCustomerUser').val()!==''){GetCustomerTickets($('#SelectedCustomerUser').val());}
if($('#CustomerInfo').length){BackupData.CustomerInfo=$('#CustomerInfo .Content').html();}
if(isJQueryObject($Element)){$Element.off('keyup.Validate').on('keyup.Validate',function(){var Value=$Element.val();if($Element.hasClass('ServerError')&&Value.length){$('#OTRS_UI_Tooltips_ErrorTooltip').hide();}});Core.App.Subscribe('Event.CustomerUserAddressBook.AddTicketCustomer.Callback.'+$Element.attr('id'),function(UserLogin,CustomerTicketText){$Element.val(CustomerTicketText);TargetNS.AddTicketCustomer($Element.attr('id'),CustomerTicketText,UserLogin);});Core.UI.Autocomplete.Init($Element,function(Request,Response){var URL=Core.Config.Get('Baselink'),Data={Action:'AgentCustomerSearch',Term:Request.term,MaxResults:Core.UI.Autocomplete.GetConfig('MaxResultsDisplayed')};$Element.data('AutoCompleteXHR',Core.AJAX.FunctionCall(URL,Data,function(Result){var ValueData=[];$Element.removeData('AutoCompleteXHR');$.each(Result,function(){ValueData.push({label:this.Label+" ("+this.Value+")",value:this.Label,key:this.Value});});Response(ValueData);}));},function(Event,UI){var CustomerKey=UI.item.key,CustomerValue=UI.item.value;BackupData.CustomerKey=CustomerKey;BackupData.CustomerEmail=CustomerValue;$Element.val(CustomerValue);if(Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketCompose'||Core.Config.Get('Action')==='AgentTicketForward'||Core.Config.Get('Action')==='AgentTicketEmailOutbound'||Core.Config.Get('Action')==='AgentTicketEmailResend')
{$Element.val('');}
if(Core.Config.Get('Action')!=='AgentTicketPhone'&&Core.Config.Get('Action')!=='AgentTicketEmail'&&Core.Config.Get('Action')!=='AgentTicketCompose'&&Core.Config.Get('Action')!=='AgentTicketForward'&&Core.Config.Get('Action')!=='AgentTicketEmailOutbound'&&Core.Config.Get('Action')!=='AgentTicketEmailResend')
{$('#SelectedCustomerUser').val(CustomerKey);ActivateSelectionCustomerID();if($('#CustomerUserID').length){$('#CustomerUserID').val(CustomerKey);if($('#CustomerUserOption').length){$('#CustomerUserOption').val(CustomerKey);}
else{$('<input type="hidden" name="CustomerUserOption" id="CustomerUserOption">').val(CustomerKey).appendTo($Element.closest('form'));}}
GetCustomerTickets(CustomerKey);GetCustomerInfo(CustomerKey);}
else{TargetNS.AddTicketCustomer($(Event.target).attr('id'),CustomerValue,CustomerKey);}},'CustomerSearch');$Element.on('autocompletefocus',function(){AutocompleteFocus=true;});$Element.on('autocompleteclose',function(Event){if(AutocompleteFocus&&(Event.originalEvent===undefined||(Event.originalEvent&&Event.originalEvent.type=='blur')))
{AutocompleteFocus=true;$Element.val('');}});if(Core.Config.Get('Action')!=='AgentTicketPhone'&&Core.Config.Get('Action')!=='AgentTicketEmail'&&Core.Config.Get('Action')!=='AgentTicketCompose'&&Core.Config.Get('Action')!=='AgentTicketForward'&&Core.Config.Get('Action')!=='AgentTicketEmailOutbound'&&Core.Config.Get('Action')!=='AgentTicketEmailResend')
{$Element.blur(function(){var FieldValue=$(this).val();if(FieldValue!==BackupData.CustomerEmail&&FieldValue!==BackupData.CustomerKey){$('#SelectedCustomerUser').val('');$('#CustomerUserID').val('');$('#CustomerID').val('');$('#CustomerUserOption').val('');$('#ShowCustomerID').html('');if(Core.Config.Get('Action')!=='AgentTicketCustomer'){$('#CustomerInfo .Content').html(BackupData.CustomerInfo);}
if(Core.Config.Get('Action')==='AgentTicketProcess'&&typeof Core.Config.Get('CustomerFieldsToUpdate')!=='undefined'){Core.AJAX.FormUpdate($('#CustomerID').closest('form'),'AJAXUpdate','ServiceID',Core.Config.Get('CustomerFieldsToUpdate'));}}});}
else{TargetNS.InitCustomerField($Element);}}
$(window).on('beforeunload.CustomerSearch',function(){$('#SelectedCustomerUser').val('');return;});CheckPhoneCustomerCountLimit();};function htmlDecode(Text){return Text.replace(/&amp;/g,'&');}
TargetNS.AddTicketCustomer=function(Field,CustomerValue,CustomerKey,SetAsTicketCustomer){var $Clone=$('.CustomerTicketTemplate'+Field).clone(),CustomerTicketCounter=$('#CustomerTicketCounter'+Field).val(),TicketCustomerIDs=0,IsDuplicated=false,IsFocused=($(document.activeElement).attr('id')==Field),Suffix;if(typeof CustomerKey!=='undefined'){CustomerKey=htmlDecode(CustomerKey);}
if(CustomerValue===''){return false;}
$('[class*=CustomerTicketText]').each(function(){if($(this).val()===CustomerValue){IsDuplicated=true;}});if(IsDuplicated){TargetNS.ShowDuplicatedDialog(Field);return false;}
TicketCustomerIDs=$('.CustomerContainer input[type="radio"]').length;CustomerTicketCounter++;Suffix='_'+CustomerTicketCounter;$Clone.removeClass('Hidden CustomerTicketTemplate'+Field);$Clone.find(':input, a').each(function(){var ID=$(this).attr('id');$(this).attr('id',ID+Suffix);$(this).val(CustomerValue);if(ID!=='CustomerSelected'){$(this).attr('name',ID+Suffix);}
if($(this).hasClass('CustomerTicketRadio')){if(TicketCustomerIDs===0){$(this).prop('checked',true);}
$(this).val(CustomerTicketCounter);$(this).on('change',function(){if($(this).prop('checked')){TargetNS.ReloadCustomerInfo(CustomerKey);}
return false;});}
if($(this).hasClass('CustomerKey')){$(this).val(CustomerKey);}
if($(this).hasClass('RemoveButton')){$(this).on('click',function(){TargetNS.RemoveCustomerTicket($(this));if($('#TicketCustomerContent'+Field+' .CustomerTicketRadio').length===0){$('#CustomerTickets').empty();}
return false;});$(this).val(CustomerValue);}});$('#TicketCustomerContent'+Field).parent().removeClass('Hidden');$('#TicketCustomerContent'+Field).append($Clone);$('#CustomerTicketCounter'+Field).val(CustomerTicketCounter);if((CustomerKey!==''&&TicketCustomerIDs===0&&(Field==='ToCustomer'||Field==='FromCustomer'))||SetAsTicketCustomer){if(SetAsTicketCustomer){$('#CustomerSelected_'+CustomerTicketCounter).prop('checked',true).trigger('change');}
else{$('.CustomerContainer input[type="radio"]:first').prop('checked',true).trigger('change');}}
$('#'+Field).val('');if(IsFocused){$('#'+Field).focus();}
CheckPhoneCustomerCountLimit();if((Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketCompose'||Core.Config.Get('Action')==='AgentTicketForward'||Core.Config.Get('Action')==='AgentTicketEmailOutbound'||Core.Config.Get('Action')==='AgentTicketEmailResend')&&$('#CryptKeyID').length)
{Core.AJAX.FormUpdate($('#'+Field).closest('form'),'AJAXUpdate','',['CryptKeyID']);}
$('#FromCustomer, #ToCustomer')
.removeClass('Error ServerError')
.closest('.Field')
.prev('label')
.removeClass('LabelError');Core.Form.ErrorTooltips.HideTooltip();ActivateSelectionCustomerID();return false;};TargetNS.RemoveCustomerTicket=function(Object){var TicketCustomerIDs=0,$Field=Object.closest('.Field'),$Form;if(Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketCompose'||Core.Config.Get('Action')==='AgentTicketForward'||Core.Config.Get('Action')==='AgentTicketEmailOutbound'||Core.Config.Get('Action')==='AgentTicketEmailResend')
{$Form=Object.closest('form');}
Object.parent().remove();TicketCustomerIDs=$('.CustomerContainer input[type="radio"]').length;if(TicketCustomerIDs===0){TargetNS.ResetCustomerInfo();}
if((Core.Config.Get('Action')==='AgentTicketEmail'||Core.Config.Get('Action')==='AgentTicketCompose'||Core.Config.Get('Action')==='AgentTicketForward'||Core.Config.Get('Action')==='AgentTicketEmailOutbound'||Core.Config.Get('Action')==='AgentTicketEmailResend')&&$('#CryptKeyID').length)
{Core.AJAX.FormUpdate($Form,'AJAXUpdate','',['CryptKeyID']);}
if(!$('.CustomerContainer input[type="radio"]').is(':checked')){$('.CustomerContainer input[type="radio"]:first').prop('checked',true).trigger('change');}
if($Field.find('.CustomerTicketText:visible').length===0){$Field.addClass('Hidden');DeactivateSelectionCustomerID();}
CheckPhoneCustomerCountLimit();};TargetNS.ResetCustomerInfo=function(){$('#SelectedCustomerUser').val('');$('#CustomerUserID').val('');$('#CustomerID').val('');$('#CustomerUserOption').val('');$('#ShowCustomerID').html('');$('#CustomerInfo .Content').html(Core.Language.Translate('none'));};TargetNS.ReloadCustomerInfo=function(CustomerKey){GetCustomerTickets(CustomerKey);GetCustomerInfo(CustomerKey);$('#SelectedCustomerUser').val(CustomerKey);};TargetNS.InitCustomerField=function($Element){var ObjectId=$Element.attr('id');$('#'+ObjectId).on('change',function(){if(!$('#'+ObjectId).val()||$('#'+ObjectId).val()===''){return false;}
if(!Core.UI.Autocomplete.GetConfig('ActiveAutoComplete')){if(typeof CustomerFieldChangeRunCount[ObjectId]==='undefined'){CustomerFieldChangeRunCount[ObjectId]=1;}
else{CustomerFieldChangeRunCount[ObjectId]++;}
if(Core.UI.Autocomplete.SearchButtonClicked[ObjectId]){delete CustomerFieldChangeRunCount[ObjectId];delete Core.UI.Autocomplete.SearchButtonClicked[ObjectId];return false;}
else{if(CustomerFieldChangeRunCount[ObjectId]===1){window.setTimeout(function(){$('#'+ObjectId).trigger('change');},200);return false;}
delete CustomerFieldChangeRunCount[ObjectId];}}
if($Element.autocomplete("widget").is(':visible')){window.setTimeout(function(){$('#'+ObjectId).trigger('change');},200);return false;}
Core.Agent.CustomerSearch.AddTicketCustomer(ObjectId,$('#'+ObjectId).val());return false;});$('#'+ObjectId).on('keypress',function(e){if(e.which===13){Core.Agent.CustomerSearch.AddTicketCustomer(ObjectId,$('#'+ObjectId).val());return false;}});};TargetNS.ShowDuplicatedDialog=function(Field){Core.UI.Dialog.ShowAlert(Core.Language.Translate('Duplicated entry'),Core.Language.Translate('This address already exists on the address list.')+' '+Core.Language.Translate('It is going to be deleted from the field, please try again.'),function(){Core.UI.Dialog.CloseDialog($('.Alert'));$('#'+Field).val('');$('#'+Field).focus();return false;});};return TargetNS;}(Core.Agent.CustomerSearch||{}));

"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.CustomerSearchAutoComplete=(function(TargetNS){TargetNS.Init=function(){$("#CustomerAutoComplete, .CustomerAutoComplete").each(function(){Core.Agent.CustomerSearch.Init($(this));});};Core.Init.RegisterNamespace(TargetNS,'APP_MODULE');return TargetNS;}(Core.Agent.CustomerSearchAutoComplete||{}));

"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.TicketAction=(function(TargetNS){function SerializeData(Data){var QueryString='';$.each(Data,function(Key,Value){QueryString+=';'+encodeURIComponent(Key)+'='+encodeURIComponent(Value);});return QueryString;}
function OpenCustomerUserAddressBook(RecipientField,RecipientFieldLabel,RecipientType){var CustomerUserAddressBookIFrameURL,CustomerUserAddressBookIFrame;CustomerUserAddressBookIFrameURL=Core.Config.Get('CGIHandle')+'?Action=AgentCustomerUserAddressBook;RecipientField='+RecipientField+';RecipientFieldLabel='+RecipientFieldLabel+';RecipientType='+RecipientType;CustomerUserAddressBookIFrameURL+=SerializeData(Core.App.GetSessionInformation());CustomerUserAddressBookIFrame='<iframe class="TextOption CustomerUserAddressBook" src="'+CustomerUserAddressBookIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(CustomerUserAddressBookIFrame,'','10px','Center',true);}
function OpenCustomerDialog(){var CustomerIFrameURL,CustomerIFrame;CustomerIFrameURL=Core.Config.Get('CGIHandle')+'?Action=AdminCustomerUser;Nav=None;Subject=;What=';CustomerIFrameURL+=SerializeData(Core.App.GetSessionInformation());CustomerIFrame='<iframe class="TextOption Customer" src="'+CustomerIFrameURL+'"></iframe>';Core.UI.Dialog.ShowContentDialog(CustomerIFrame,'','10px','Center',true);}
function OpenCustomerIDSelection(){var Data={Action:'AgentCustomerSearch',Subaction:'AssignedCustomerIDs',CustomerUserID:$('#SelectedCustomerUser').val(),};$('#SelectionCustomerIDAssigned').empty();Core.AJAX.FunctionCall(Core.Config.Get('Baselink'),Data,function(Response){$.each(Response,function(Index,CustomerID){var CustomerIDOption=new Option(CustomerID,CustomerID);CustomerIDOption.innerHTML=CustomerID;$('#SelectionCustomerIDAssigned').append(CustomerIDOption);});if(!$('#SelectionCustomerIDAssigned > option').length){$('#TemplateSelectionCustomerID fieldset:last').addClass('Hidden');}
else{$('#TemplateSelectionCustomerID fieldset:last').removeClass('Hidden');}
Core.UI.Dialog.ShowContentDialog($('#TemplateSelectionCustomerID'),Core.Language.Translate('Select a customer ID to assign to this ticket'),'10px','Center',true);Core.Agent.CustomerSearch.InitSimple($('#SelectionCustomerIDAll'));$('#SelectionCustomerIDAssigned').val($('#CustomerID').val()).trigger('redraw.InputField').trigger('change');$('#SelectionCustomerIDAll').on('select.Autocomplete',function(){CloseCustomerIDSelection($(this).val());});$('#SelectionCustomerIDAssigned').on('change',function(){CloseCustomerIDSelection($(this).val());});});}
function CloseCustomerIDSelection(CustomerID){$('#CustomerID').val(CustomerID);$('#ShowCustomerID').html(CustomerID);Core.UI.Dialog.CloseDialog($('.Dialog'));}
function MarkPrimaryCustomer(){$('.CustomerContainer').children('div').each(function(){var $InputObj=$(this).find('.CustomerTicketText'),$RadioObj=$(this).find('.CustomerTicketRadio');if($RadioObj.prop('checked')){$InputObj.addClass('MainCustomer');}
else{$InputObj.removeClass('MainCustomer');}});}
TargetNS.Init=function(){$('.OptionCustomerUserAddressBook').on('click',function(){OpenCustomerUserAddressBook($(this).data('recipient-field'),$(this).data('recipient-field-label'),$(this).data('recipient-type'));return false;});$('#OptionCustomer').on('click',function(){OpenCustomerDialog();return false;});$('#SelectionCustomerID').on('click',function(){OpenCustomerIDSelection();return false;});Core.UI.InputFields.Deactivate($('#TemplateSelectionCustomerID'));MarkPrimaryCustomer();Core.App.Subscribe('Event.Agent.CustomerSearch.GetCustomerInfo.Callback',function(){MarkPrimaryCustomer();});$('#submitRichText').on('click',function(Event){var ToCustomer=$('#ToCustomer').val()||'',CcCustomer=$('#CcCustomer').val()||'',BccCustomer=$('#BccCustomer').val()||'',FromCustomer=$('#FromCustomer').val()||'';if(ToCustomer.length||CcCustomer.length||BccCustomer.length||FromCustomer.length){window.setTimeout(function(){$('#submitRichText').trigger('click');},100);Event.preventDefault();Event.stopPropagation();return false;}});Core.App.Subscribe('Event.UI.ToggleWidget',function($WidgetElement){if($WidgetElement.attr('id')!=='WidgetArticle'){return;}
if($WidgetElement.hasClass('Expanded')){$('#CreateArticle').prop('checked',true);}});};TargetNS.UpdateCustomer=function(Customer){var $UpdateForm=$('form[name=compose]',parent.document);$UpdateForm
.find('#ExpandCustomerName').val('2')
.end()
.find('#PreSelectedCustomerUser').val(Customer)
.end()
.submit();parent.Core.UI.Dialog.CloseDialog($('.Dialog',parent.document));};TargetNS.SelectRadioButton=function(Value,Name){$('input[type="radio"][name='+Name+'][value='+Value+']').prop('checked',true);};TargetNS.ConfirmTemplateOverwrite=function(FieldName,$TemplateSelect,Callback){var Content='',LastValue=$TemplateSelect.data('LastValue')||'';Content=$('#'+FieldName).val();if(typeof CKEDITOR!=='undefined'&&CKEDITOR.instances[FieldName]){Content=CKEDITOR.instances[FieldName].getData();}
if(Content.length&&!window.confirm(Core.Language.Translate('Setting a template will overwrite any text or attachment.')+' '+Core.Language.Translate('Do you really want to continue?')))
{$TemplateSelect.val(LastValue).trigger('redraw');}
else if($.isFunction(Callback)){Callback();$TemplateSelect.data('LastValue',$TemplateSelect.val());}}
Core.Init.RegisterNamespace(TargetNS,'APP_MODULE');return TargetNS;}(Core.Agent.TicketAction||{}));

"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.TicketPhone=(function(TargetNS){TargetNS.Init=function(){var DynamicFieldNames=Core.Config.Get('DynamicFieldNames'),FromExternalCustomerName=Core.Config.Get('FromExternalCustomerName'),FromExternalCustomerEmail=Core.Config.Get('FromExternalCustomerEmail'),Fields=['TypeID','Dest','NewUserID','NewResponsibleID','NextStateID','PriorityID','ServiceID','SLAID'],ModifiedFields;$('.CustomerTicketRadio').on('change',function(){var CustomerKey;if($(this).prop('checked')){CustomerKey=$('#CustomerKey_'+$(this).val()).val();Core.Agent.CustomerSearch.ReloadCustomerInfo(CustomerKey);}
return false;});$('.CustomerTicketRemove').on('click',function(){Core.Agent.CustomerSearch.RemoveCustomerTicket($(this));return false;});if(typeof FromExternalCustomerEmail!=='undefined'&&typeof FromExternalCustomerName!=='undefined'){Core.Agent.CustomerSearch.AddTicketCustomer('FromCustomer',FromExternalCustomerEmail,FromExternalCustomerName,true);}
$.each(Fields,function(Index,Value){ModifiedFields=Core.Data.CopyObject(Fields).concat(DynamicFieldNames);ModifiedFields.splice(Index,1);FieldUpdate(Value,ModifiedFields);});$('#OwnerSelectionGetAll').on('click',function(){$('#OwnerAll').val('1');Core.AJAX.FormUpdate($('#NewPhoneTicket'),'AJAXUpdate','OwnerAll',['NewUserID'],function(){$('#NewUserID').focus();});return false;});$('#ResponsibleSelectionGetAll').on('click',function(){$('#ResponsibleAll').val('1');Core.AJAX.FormUpdate($('#NewPhoneTicket'),'AJAXUpdate','ResponsibleAll',['NewResponsibleID'],function(){$('#NewResponsibleID').focus();});return false;});$('#StandardTemplateID').on('change',function(){Core.Agent.TicketAction.ConfirmTemplateOverwrite('RichText',$(this),function(){Core.AJAX.FormUpdate($('#NewPhoneTicket'),'AJAXUpdate','StandardTemplateID',['RichTextField']);});return false;});Core.Agent.TicketAction.Init();};function FieldUpdate(Value,ModifiedFields){$('#'+Value).on('change',function(){Core.AJAX.FormUpdate($('#NewPhoneTicket'),'AJAXUpdate',Value,ModifiedFields);});}
Core.Init.RegisterNamespace(TargetNS,'APP_MODULE');return TargetNS;}(Core.Agent.TicketPhone||{}));

"use strict";var Core=Core||{};Core.Agent=Core.Agent||{};Core.Agent.TicketSplit=(function(TargetNS){TargetNS.OpenSplitSelection=function(DataHref){var DataHrefArray=DataHref.split(';'),TicketIDArray=DataHrefArray[1].split('='),ArticleIDArray=DataHrefArray[2].split('='),LinkTicketIDArray=DataHrefArray[3].split('='),Data={Action:'AgentSplitSelection',TicketID:TicketIDArray[1],ArticleID:ArticleIDArray[1],LinkTicketID:LinkTicketIDArray[1]};Core.UI.Dialog.ShowWaitingDialog(Core.Config.Get('LoadingMsg'),Core.Config.Get('LoadingMsg'));Core.UI.InputFields.Activate($('#SplitSelection'));Core.AJAX.FunctionCall(Core.Config.Get('CGIHandle'),Data,function(HTML){var URL;if(!$('.Dialog:visible').length){return;}
Core.UI.Dialog.ShowContentDialog(HTML,Core.Language.Translate("Split"),'20%','Center',true);$('#SplitSelection').unbind('change.SplitSelection').bind('change.SplitSelection',function(){if($('#SplitSelection').val()=='ProcessTicket'){$('#ProcessSelectionLabel').fadeIn();$('#ProcessSelection').fadeIn();Core.UI.InputFields.Activate();}
else{$('#ProcessSelectionLabel').fadeOut();$('#ProcessSelection').fadeOut();}});$('#SplitSubmit').off('click').on('click',function(){if($('#SplitSelection').val()=='ProcessTicket'){$('<input/>')
.attr('type','hidden')
.attr('name','ProcessEntityID')
.attr('value',$('#ProcessEntityID').val())
.appendTo($('#AgentSplitSelection'));}
if(Core.UI.Popup!==undefined&&Core.UI.Popup.CurrentIsPopupWindow()){URL=Core.Config.Get('Baselink')+$('#AgentSplitSelection').serialize();Core.UI.Popup.ExecuteInParentWindow(function(WindowObject){WindowObject.Core.UI.Popup.FirePopupEvent('URL',{URL:URL});});Core.UI.Popup.ClosePopup();}
else{$('#AgentSplitSelection').submit();}});},'html');};Core.Init.RegisterNamespace(TargetNS,'APP_MODULE');return TargetNS;}(Core.Agent.TicketSplit||{}));

